service: amazon-scraper

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  timeout: 30
  memorySize: 512
  environment:
    NODE_ENV: production
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

functions:
  scrapeAmazonSponsoredProducts:
    handler: dist/lambda-handler.scrapeAmazonSponsoredProducts
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /scrape
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                q: false
                search: false

# plugins:
  # - serverless-plugin-typescript

package:
  patterns:
    - '!test/**'
    - '!*.md'
    - '!.git/**'
    - '!src/__tests__/**'